SELECT * FROM Tabela ORDER BY Col2;   --SE QUISER QUE ORDENE A PARTIR DA COLUNA 2 EM ORDEM CRESCENTE

SELECT * FROM Tabela ORDER BY Col2 DESC;  --SE QUISER QUE ORDENE A PARTIR DA COLUNA 2 EM ORDEM DECRESCENTE